### ISSUE TITLE
OpenSSL::SSL::SSLError at /signin

### ISSUE THREAD

**Issue by mariordiaz** [lfcipriani/sign_in_with_twitter_sample#2]
Hello, 
I downloaded this projects and followed all instructions but I am getting 

OpenSSL::SSL::SSLError at /signin
SSL_connect returned=1 errno=0 state=error: certificate verify failed
file: http.rb location: connect_nonblock line: 933
BACKTRACE
(expand)
JUMP TO: GET POST COOKIES ENV
C:/ProgramFiles/Ruby23-x64/lib/ruby/2.3.0/net/http.rb in connect_nonblock
              case s.connect_nonblock(exception: false)
C:/ProgramFiles/Ruby23-x64/lib/ruby/2.3.0/net/http.rb in connect
              case s.connect_nonblock(exception: false)
C:/ProgramFiles/Ruby23-x64/lib/ruby/2.3.0/net/http.rb in do_start
      connect
C:/ProgramFiles/Ruby23-x64/lib/ruby/2.3.0/net/http.rb in start
          do_start
C:/ProgramFiles/Ruby23-x64/lib/ruby/2.3.0/net/http.rb in request
        start {
C:/Users/Mario/Documents/Development/PhotoShelter/Source/sign_in_with_twitter_sample-master/sign_in_with_twitter_sample-master/lib/twitter_sign_in.rb in request
      http.request(req)
C:/Users/Mario/Documents/Development/PhotoShelter/Source/sign_in_with_twitter_sample-master/sign_in_with_twitter_sample-master/lib/twitter_sign_in.rb in request_token
      response = TwitterSignIn.request(
app.rb in block in <main>
  token = TwitterSignIn.request_token
GET
No GET data.
POST
No POST data.
COOKIES
Variable	Value
rack.session	
"BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTJiMTJkNGM5MTVjMzFlMTA3ZGRh\nOTcyYzE3N2M5NDY0ODVkYmFkMzdmZDZjMjUyOGNhMjIxMTk1MDVmMDRmZDkG\nOwBGSSIJY3NyZgY7AEZJIiU5MjQ5ZjNiZmRjMDlhMjU2MjQwMWQ5NmMyZDA3\nZjljMwY7AEZJIg10cmFja2luZwY7AEZ7B0kiFEhUVFBfVVNFUl9BR0VOVAY7\nAFRJIi0wMDE2ODNjYjM2NjRhOGNiN2FhYzYzNmZjYTJiNDYxNTcwMzliZmZk\nBjsARkkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsAVEkiLWJjMjRkNjU2YzYy\nNmE5YjQ5ODIzZDhkYWQ2NWU2Yjc4NjQzNTkyOTkGOwBG\n--91a55b2a559e6a69aed2a2de924f6df3b7970af5"
Rack ENV
Variable	Value
GATEWAY_INTERFACE	
CGI/1.2
HTTP_ACCEPT	
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_ACCEPT_ENCODING	
gzip, deflate, sdch, br
HTTP_ACCEPT_LANGUAGE	
en-US,en;q=0.8,es;q=0.6
HTTP_CONNECTION	
keep-alive
HTTP_COOKIE	
rack.session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTJiMTJkNGM5MTVjMzFlMTA3ZGRh%0AOTcyYzE3N2M5NDY0ODVkYmFkMzdmZDZjMjUyOGNhMjIxMTk1MDVmMDRmZDkG%0AOwBGSSIJY3NyZgY7AEZJIiU5MjQ5ZjNiZmRjMDlhMjU2MjQwMWQ5NmMyZDA3%0AZjljMwY7AEZJIg10cmFja2luZwY7AEZ7B0kiFEhUVFBfVVNFUl9BR0VOVAY7%0AAFRJIi0wMDE2ODNjYjM2NjRhOGNiN2FhYzYzNmZjYTJiNDYxNTcwMzliZmZk%0ABjsARkkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsAVEkiLWJjMjRkNjU2YzYy%0ANmE5YjQ5ODIzZDhkYWQ2NWU2Yjc4NjQzNTkyOTkGOwBG%0A--91a55b2a559e6a69aed2a2de924f6df3b7970af5
HTTP_HOST	
localhost:4567
HTTP_REFERER	
http://localhost:4567/
HTTP_UPGRADE_INSECURE_REQUESTS	
1
HTTP_USER_AGENT	
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.12.2924.87 Safari/537.36
HTTP_VERSION	
HTTP/1.1
PATH_INFO	
/signin
QUERY_STRING	
REMOTE_ADDR	
::1
REQUEST_METHOD	
GET
REQUEST_PATH	
/signin
REQUEST_URI	
/signin
SCRIPT_NAME	
SERVER_NAME	
localhost
SERVER_PORT	
4567
SERVER_PROTOCOL	
HTTP/1.1
SERVER_SOFTWARE	
puma 3.8.2 Sassy Salamander
puma.config	
#<Puma::Configuration:0x0000000405f650 @options=#<Puma::UserFileDefaultOptions:0x0000000405f448 @user_options={:Port=>4567, :Host=>"localhost", :log_requests=>false, :binds=>["tcp://localhost:4567"], :app=>Sinatra::Application, :environment=>"development"}, @file_options={}, @default_options={:min_threads=>0, :max_threads=>16, :log_requests=>false, :debug=>false, :binds=>["tcp://0.0.0.0:9292"], :workers=>0, :daemon=>false, :mode=>:http, :worker_timeout=>60, :worker_boot_timeout=>60, :worker_shutdown_timeout=>30, :remote_address=>:socket, :tag=>"sign_in_with_twitter_sample-master", :environment=>"development", :rackup=>"config.ru", :logger=>#<IO:<STDOUT>>, :persistent_timeout=>20, :Verbose=>false, :Silent=>false}>, @plugins=#<Puma::PluginLoader:0x0000000405f3f8 @instances=[]>, @user_dsl=#<Puma::DSL:0x0000000405f3a8 @config=#<Puma::Configuration:0x0000000405f650 ...>, @options={:Port=>4567, :Host=>"localhost", :log_requests=>false, :binds=>["tcp://localhost:4567"], :app=>Sinatra::Application, :environment=>"development"}, @plugins=[]>, @file_dsl=#<Puma::DSL:0x0000000405f358 @config=#<Puma::Configuration:0x0000000405f650 ...>, @options={}, @plugins=[]>, @default_dsl=#<Puma::DSL:0x0000000405f308 @config=#<Puma::Configuration:0x0000000405f650 ...>, @options={:min_threads=>0, :max_threads=>16, :log_requests=>false, :debug=>false, :binds=>["tcp://0.0.0.0:9292"], :workers=>0, :daemon=>false, :mode=>:http, :worker_timeout=>60, :worker_boot_timeout=>60, :worker_shutdown_timeout=>30, :remote_address=>:socket, :tag=>"sign_in_with_twitter_sample-master", :environment=>"development", :rackup=>"config.ru", :logger=>#<IO:<STDOUT>>, :persistent_timeout=>20, :Verbose=>false, :Silent=>false}, @plugins=[]>>
puma.socket	
#<TCPSocket:fd 9>
rack.after_reply	
[]
rack.errors	
#<Object:0x00000002fd4010>
rack.hijack	
#<Puma::Client:0x26190ac @ready=true>
rack.hijack?	
true
rack.input	
#<Puma::NullIO:0x00000003fe7e48>
rack.logger	
#<Logger:0x00000004c68e88 @progname=nil, @level=1, @default_formatter=#<Logger::Formatter:0x00000004c68e60 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00000004c68e10 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00000004c68de8>>>
rack.multiprocess	
false
rack.multithread	
true
rack.request.cookie_hash	
{"rack.session"=>"BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTJiMTJkNGM5MTVjMzFlMTA3ZGRh\nOTcyYzE3N2M5NDY0ODVkYmFkMzdmZDZjMjUyOGNhMjIxMTk1MDVmMDRmZDkG\nOwBGSSIJY3NyZgY7AEZJIiU5MjQ5ZjNiZmRjMDlhMjU2MjQwMWQ5NmMyZDA3\nZjljMwY7AEZJIg10cmFja2luZwY7AEZ7B0kiFEhUVFBfVVNFUl9BR0VOVAY7\nAFRJIi0wMDE2ODNjYjM2NjRhOGNiN2FhYzYzNmZjYTJiNDYxNTcwMzliZmZk\nBjsARkkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsAVEkiLWJjMjRkNjU2YzYy\nNmE5YjQ5ODIzZDhkYWQ2NWU2Yjc4NjQzNTkyOTkGOwBG\n--91a55b2a559e6a69aed2a2de924f6df3b7970af5"}
rack.request.cookie_string	
rack.session=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiRTJiMTJkNGM5MTVjMzFlMTA3ZGRh%0AOTcyYzE3N2M5NDY0ODVkYmFkMzdmZDZjMjUyOGNhMjIxMTk1MDVmMDRmZDkG%0AOwBGSSIJY3NyZgY7AEZJIiU5MjQ5ZjNiZmRjMDlhMjU2MjQwMWQ5NmMyZDA3%0AZjljMwY7AEZJIg10cmFja2luZwY7AEZ7B0kiFEhUVFBfVVNFUl9BR0VOVAY7%0AAFRJIi0wMDE2ODNjYjM2NjRhOGNiN2FhYzYzNmZjYTJiNDYxNTcwMzliZmZk%0ABjsARkkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsAVEkiLWJjMjRkNjU2YzYy%0ANmE5YjQ5ODIzZDhkYWQ2NWU2Yjc4NjQzNTkyOTkGOwBG%0A--91a55b2a559e6a69aed2a2de924f6df3b7970af5
rack.request.query_hash	
{}
rack.request.query_string	
rack.run_once	
false
rack.session	
{"session_id"=>"2b12d4c915c31e107dda972c177c946485dbad37fd6c2528ca22119505f04fd9", "csrf"=>"9249f3bfdc09a2562401d96c2d07f9c3", "tracking"=>{"HTTP_USER_AGENT"=>"001683cb3664a8cb7aac636fca2b46157039bffd", "HTTP_ACCEPT_LANGUAGE"=>"bc24d656c626a9b49823d8dad65e6b7864359299"}}
rack.session.options	
{:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :sidbits=>128, :secure_random=>SecureRandom, :secret=>"this is super secret, unless you read this file", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x000000041c5008>}
rack.session.unpacked_cookie_data	
{"session_id"=>"2b12d4c915c31e107dda972c177c946485dbad37fd6c2528ca22119505f04fd9", "csrf"=>"9249f3bfdc09a2562401d96c2d07f9c3", "tracking"=>{"HTTP_USER_AGENT"=>"001683cb3664a8cb7aac636fca2b46157039bffd", "HTTP_ACCEPT_LANGUAGE"=>"bc24d656c626a9b49823d8dad65e6b7864359299"}}
rack.url_scheme	
http
rack.version	
[1, 3]
sinatra.accept	
[#<Sinatra::Request::AcceptEntry:0x00000004c98278 @entry="text/html", @type="text/html", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00000004c980e8 @entry="application/xhtml+xml", @type="application/xhtml+xml", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00000004cb3b90 @entry="image/webp", @type="image/webp", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00000004cb3f00 @entry="application/xml;q=0.9", @type="application/xml", @params={}, @q=0.9>, #<Sinatra::Request::AcceptEntry:0x00000004cb3a00 @entry="*/*;q=0.8", @type="*/*", @params={}, @q=0.8>]
sinatra.commonlogger	
true
sinatra.error	
#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed>
sinatra.route	
GET /signin
You're seeing this error because you have enabled the show_exceptions setti

**Comment by lfcipriani** [comment]
Hi Mario,

You are having this issue because the OpenSSL ruby library cannot find any certificates to trust when trying to do HTTPS requests. The code for this sample rely on the fact that you have the defaults, which it seems you don't have it. I found some links that explains better what the issue is and how to solve:

- http://railsapps.github.io/openssl-certificate-verify-failed.html
- https://gist.github.com/mislav/5026283

And if you want a really good resource to learn more about the context, check this:

- http://mislav.net/2013/07/ruby-openssl/

**Comment by mariordiaz** [comment]
It was necessary to install a cert in the machine. I fixed the issues following the instructions here: 
https://gist.github.com/fnichol/867550
